### ISSUE TITLE
Feature: Add ability to directly link to a token info page

### ISSUE THREAD

**Issue by the-hoskinsons** [eneakao/ergotokens#1]
It would be helpful to be able to link directly to a specific token ID on ergotokens.org. 

For example, right now to view token info on token ID 6a01aadae9df3f5f83fb51156dedba9fa2ec1631dd44d7bac09cc6908116491d, you have to navigate to ergotokens.org and then manually paste the token ID and select token name (ErgoHoskinsons #2). It would be great if this could be put into a link that includes the required info and displays the page. This came up because we are auctioning and tweeting about this NFT and want to be able to provide a single link that includes all the info for verification. 

For example:
ergotokens.org/token/6a01aadae9df3f5f83fb51156dedba9fa2ec1631dd44d7bac09cc6908116491d

or

ergotokens.org/token/6a01aadae9df3f5f83fb51156dedba9fa2ec1631dd44d7bac09cc6908116491d/ErgoHoskinsons%20%232

or

ergotokens.org/token/6a01aadae9df3f5f83fb51156dedba9fa2ec1631dd44d7bac09cc6908116491d/1

Thank you!

**Comment by ladopixel** [comment]
Hi the-hoskinsons, I'm a fan of your nfts, I hope one day to have one of your NFTs :)

I'm working on this functionality for ErgoTokens.org, but I already have it active on the ErgoNFTs.org website, you can see yours there >> https://ergonfts.org/#/?token=6a01aadae9df3f5f83fb51156dedba9fa2ec1631dd44d7bac09cc6908116491d

Regards!

**Comment by the-hoskinsons** [comment]
Perfect — thank you!

And thanks for your support of our project. If you share a Cardano wallet
address, I would love to send you an NFT from our original collection. I
have a small personal collection I randomly kept from the original drop for
this purpose ;)

**Comment by ladopixel** [comment]
Thank you very much! Here is an address. >> addr1qxagfv7vscj5pw857uvgre98cz0w6m8m78u40h03sqh406geceglrmgte7esejwe53grpssvtrymx8z8yrymh6duyqfspd9hh2

**Comment by the-hoskinsons** [comment]
Welcome! Sent ✓

and thanks again for your work on Ergo ;)

**Comment by ladopixel** [comment]
Thank you! I have already received it, is there any website to see the image officially?

**Comment by the-hoskinsons** [comment]
Welcome!

You can view your wallet in pool.pm by searching for any address from the
wallet, like this:

https://pool.pm/addr1qxagfv7vscj5pw857uvgre98cz0w6m8m78u40h03sqh406geceglrmgte7esejwe53grpssvtrymx8z8yrymh6duyqfspd9hh2

Info about the NFTs and searchable database also at
thehoskinsonscommunity.com

Our official site is thehoskinsons.com

**Comment by ladopixel** [comment]
Oh, thank you so much! It looks amazing the NFT.

**Comment by the-hoskinsons** [comment]
Welcome! Our discord is discord.gg/sWfYuasPcB by the way. Glad you like it
;)

**Comment by ladopixel** [comment]
Perfect, thanks! 👌

**Comment by ladopixel** [comment]
The update to display the details of a token from the URL is now complete >> https://ergotokens.org/#/?token=6a01aadae9df3f5f83fb51156dedba9fa2ec1631dd44d7bac09cc6908116491d

Regards!

**Comment by the-hoskinsons** [comment]
Nice work. Thanks!
